// export default{
//     [
//         {
//             code:"/joy/",
//             icon:"data:image/gif;base64,R0lGODlhAQABAJH/AP///wAAAMDAwAAAACH5BAEAAAIALAAAAAABAAEAAAICVAEAOw==",
//             name:"笑哭",
//         },{
//             code:"/kiss_heart/",
//             icon:"data:image/gif;base64,R0lGODlhAQABAJH/AP///wAAAMDAwAAAACH5BAEAAAIALAAAAAABAAEAAAICVAEAOw==",
//             name:"亲亲"
//         },{
//             code:"/heart/",
//             icon:"data:image/gif;base64,R0lGODlhAQABAJH/AP///wAAAMDAwAAAACH5BAEAAAIALAAAAAABAAEAAAICVAEAOw==",
//             name:"爱心"
//         },{
//             code:"/heart_eyes/",
//             icon:"data:image/gif;base64,R0lGODlhAQABAJH/AP///wAAAMDAwAAAACH5BAEAAAIALAAAAAABAAEAAAICVAEAOw==",
//             name:""
//         },{
//             code:"",
//             icon:"",
//             name:""
//         },{
//             code:"",
//             icon:"",
//             name:""
//         },{
//             code:"",
//             icon:"",
//             name:""
//         },{
//             code:"",
//             icon:"",
//             name:""
//         },{
//             code:"",
//             icon:"",
//             name:""
//         },{
//             code:"",
//             icon:"",
//             name:""
//         },{
//             code:"",
//             icon:"",
//             name:""
//         },{
//             code:"",
//             icon:"",
//             name:""
//         },{
//             code:"",
//             icon:"",
//             name:""
//         },{
//             code:"",
//             icon:"",
//             name:""
//         },{
//             code:"",
//             icon:"",
//             name:""
//         },{
//             code:"",
//             icon:"",
//             name:""
//         },{
//             code:"",
//             icon:"",
//             name:""
//         },{
//             code:"",
//             icon:"",
//             name:""
//         },{
//             code:"",
//             icon:"",
//             name:""
//         },{
//             code:"",
//             icon:"",
//             name:""
//         }

//     ]
// }